modLoader = 'javafml' # Neo 1.20.5+ does not need a @Mod for javafml mods
loaderVersion = '[1,)'
license = '${license}'
issueTrackerURL = '${repo}/issues'

[[mods]]
modId = 'vaultpatcher'
displayName = 'VaultPatcher'
version = '${version}'
description = '${description}'
authors = 'FengMing3093'
displayTest = 'NONE'
modUrl = '${homepage}'
displayURL = '${homepage}'
